// import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";

// // eslint-disable-next-line @typescript-eslint/ban-ts-comment
// // @ts-ignore - the server build file is generated by `remix vite:build`
// // eslint-disable-next-line import/no-unresolved
// import * as build from "../build/server";

// export const onRequest = createPagesFunctionHandler({ build });


import { Hono } from 'hono'
import { handle } from 'hono/cloudflare-pages'


const app = new Hono()

app.get('/data', (c) => c.json({ message: 'Hello from Hono!' }))

export const onRequest = handle(app)